# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2422531c29b6875858b07aeb97b89a4d8e64a92df4cedf37b5d37244f95090ed9d5c1eab313b2f26a44b7371f5a86c1f1da7c379f744a076151fb812ad3e2b92

test:
  secret_key_base: 87091cf1e5d8e1b7794adcb79b648a03cb9ed5947d9fff583e7d8d9592192278517a5a344a77b15717a31d8d676901f345646e27fe6ba77f4bf87b92f004ef68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
